In [1]:
import pandas as pd

In [ ]:
df = pd.read_csv('../Data/CoffeeData.csv')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 133 entries, 0 to 132
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   dose (g)          133 non-null    int64
 1   water temp ( C )  133 non-null    int64
 2   water vol (ml)    133 non-null    int64
 3   brew time (min)   133 non-null    object
 4   number of pours   133 non-null    int64
 5   TDS %             133 non-null    float64
dtypes: float64(1), int64(4), object(1)
memory usage: 6.4+ KB

In [ ]:
df.head()

,dose (g),water temp ( C ),water vol (ml),brew time (min),number of pours,TDS %
0,16,93,250,2:45,3,1.56
1,15,93,250,2:45,3,1.40
2,14,92,240,2:10,3,1.25
3,40,92,330,3:30,5,1.30
4,22,100,375,2:20,3,1.40

In [ ]:
df = df.drop(['Target'], axis=1)

KeyError: "['Target'] not found in axis"

In [ ]:
from datetime import timedelta

In [ ]:
x = df['brew time (min)']
def seconder(x):
    mins, secs = map(float, x.split(':'))
    td = timedelta(minutes=mins, seconds=secs)
    return td.total_seconds()

df['seconds'] = df['brew time (min)'].apply(seconder)

In [ ]:
df['seconds']

0      165.0
1      165.0
2      130.0
3      210.0
4      140.0
       ...
128    147.0
129    145.0
130    148.0
131    156.0
132    150.0
Name: seconds, Length: 133, dtype: float64

In [ ]:
df.head()

,dose (g),water temp ( C ),water vol (ml),brew time (min),number of pours,TDS %,seconds
0,16,93,250,2:45,3,1.56,165.0
1,15,93,250,2:45,3,1.40,165.0
2,14,92,240,2:10,3,1.25,130.0
3,40,92,330,3:30,5,1.30,210.0
4,22,100,375,2:20,3,1.40,140.0

In [ ]:
df = df.drop(['brew time (min)'], axis=1)

In [ ]:
df.head()

   dose (g)  water temp ( C )  water vol (ml)  number of pours  TDS %  seconds
0        16                93             250                3   1.56    165.0
1        15                93             250                3   1.40    165.0
2        14                92             240                3   1.25    130.0
3        40                92             330                5   1.30    210.0
4        22               100             375                3   1.40    140.0

In [ ]:
# df.to_csv('CoffeeDataSecUpdate.csv')